### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by ZeroByter**
This is my fork.
Not sure if I should have modified the readme the way I did or not. Let me know if to revert it.

### CODE REVIEW

**Comment by xhirazi** [comment]
ZeroByte thanks man for the PR. 
yes you can revert the Readme as i understand you point ;)

can you please tell on which platform you have test these changes? e.g React-Native, React etc

And you have removed atob and btoa of Base64, can you please revert it.

**Comment by ZeroByter** [comment]
I will revert the readme now.
I tested this on React-Native, as well as just plain Node. Works on both.
As for the atob and btoa functions, I have removed them intentionally because I don't use them in my new implementation because they don't encode binary data (usage of `str.charCodeAt` and `String.fromCharCode` is what caused my problems with binary data in the first place).
I will revert those deletions and bring back the functions if you want, just for backwards compability's sake, but I don't recommend for anyone to use them if they want to encode binary data, and instead they should use `Buffer.from(data, "binary").toString("base64")` like I did.

**Comment by cesarhilario** [comment]
This PR is interesting. Any predictions on when it will be accepted?

**Comment by xhirazi** [comment]
@cesarhilario  thanks for the reminder :P

**Pull request merged**
